# Generated by Django 2.1.3 on 2018-11-10 03:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_no', models.IntegerField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('web_page', models.CharField(max_length=255)),
                ('person_id', models.IntegerField(verbose_name='author unique id')),
            ],
        ),
        migrations.CreateModel(
            name='CsvFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.IntegerField(choices=[(1, 'Author'), (2, 'Submission'), (3, 'Review')])),
                ('file_hash', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_no', models.IntegerField()),
                ('submission_no', models.IntegerField()),
                ('review_assignment_no', models.IntegerField()),
                ('reviewer_name', models.CharField(max_length=255)),
                ('field_no', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='expertise level')),
                ('review_comments', models.TextField()),
                ('overall_evaluation_score_formatted', models.CharField(max_length=255)),
                ('overall_evaluation_score', models.IntegerField()),
                ('subreviewer_info_col_one', models.CharField(max_length=255)),
                ('subreviewer_info_col_two', models.CharField(max_length=255)),
                ('subreviewer_info_col_three', models.CharField(max_length=255)),
                ('subreviewer_info_col_four', models.CharField(max_length=255)),
                ('submission_date', models.DateField()),
                ('submission_time', models.TimeField()),
                ('recommendation_for_best_paper', models.BooleanField()),
                ('user_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataanalysis.CsvFile')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_no', models.IntegerField()),
                ('track_no', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('track_name', models.CharField(choices=[('Full Papers', 'Full Papers'), ('Short Papers', 'Short Papers'), ('Posters and Demos', 'Posters and Demos'), ('Poster/Demo 2', 'Poster/Demo 2'), ('Panels', 'Panels'), ('Doctoral Consortium', 'Doctoral Consortium'), ('Tutorials', 'Tutorials'), ('JCDL 2018 - Workshops', 'JCDL 2018 - Workshops')], max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('submitted', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('form_fields', models.CharField(max_length=255)),
                ('keywords', models.TextField()),
                ('decision', models.IntegerField(choices=[(1, 'yes'), (2, 'no'), (3, 'no decision')])),
                ('notified', models.BooleanField()),
                ('reviews_sent', models.BooleanField()),
                ('abstract', models.TextField()),
                ('user_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataanalysis.CsvFile')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='user_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataanalysis.CsvFile'),
        ),
    ]
