# Generated by Django 2.1.3 on 2018-11-10 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataanalysis', '0002_auto_20181110_0405'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCsvFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataanalysis.CsvFile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
