# Generated by Django 2.1.3 on 2018-11-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataanalysis', '0003_usercsvfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='submission_no',
            new_name='submission_id',
        ),
        migrations.AddField(
            model_name='author',
            name='is_corresponding',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
