# Generated by Django 2.1.3 on 2018-11-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataanalysis', '0005_auto_20181110_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='decision',
            field=models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject'), ('no decision', 'No decision')], max_length=255),
        ),
    ]
