# Generated by Django 2.1.3 on 2018-11-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataanalysis', '0006_auto_20181110_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='authors',
            field=models.TextField(),
        ),
    ]
