# Generated by Django 2.1.3 on 2018-11-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataanalysis', '0007_auto_20181110_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='submission_no',
            new_name='submission_id',
        ),
        migrations.AlterField(
            model_name='review',
            name='overall_evaluation_score_formatted',
            field=models.TextField(),
        ),
    ]
