# Generated by Django 2.1.3 on 2018-11-13 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataanalysis', '0008_auto_20181112_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='submission_no',
            new_name='submission_id',
        ),
    ]
